---
- name: Incident Response Playbook
  hosts: all
  tasks:
    - name: Block IP Address on Firewall
      command: iptables -A INPUT -s 10.0.2.17 -j DROP
      become: yes

    - name: Check for Unauthorized Login Attempts
      shell: tail -n 100 /var/log/auth.log | grep "authentication failure" | grep "10.0.2.17"
      register: unauthorized_login_attempts
      ignore_errors: yes

    - name: Notify Security Team
      debug:
        msg: "Potential unauthorized login attempt detected from IP 10.0.2.17. Investigate immediately."

    - name: Collect Forensic Data
      shell: tcpdump -i eth0 -w /tmp/forensic.pcap host 10.0.2.17
      async: 300
      poll: 0
      register: tcpdump_output

    - name: Wait for Forensic Data Collection to Complete
      async_status:
        jid: "{{ tcpdump_output.ansible_job_id }}"
      register: tcpdump_status
      until: tcpdump_status.finished
      retries: 30
      delay: 10

    - name: Analyze Forensic Data
      shell: tcpdump -r /tmp/forensic.pcap
      register: forensic_analysis

    - name: Notify Incident Response Team
      debug:
        msg: "Forensic analysis completed. Review the captured network traffic for f