---
- name: Update postgres servers
  hosts: servers
  become: yes

  tasks:
  - name: Ensure postgres DB is at the latest version
    ansible.builtin.apt:
      name: postgresql
      state: latest

  - name: Ensure that postgresql is started
    ansible.builtin.service:
      name: postgresql
      state: started
