---
---
- name: SQL Injection Attack | 192.155.88.231
  hosts: servers
  become: yes
  tasks:
    - name: Block IP Address at Firewall Level
      ansible.builtin.iptables:
        chain: INPUT
        source: 192.155.88.231
        jump: DROP
      become: yes
```
In this playbook:
- The playbook is named "SQL Injection Attack | 192.155.88.231" to indicate the type of attack and the attacker's IP address.
- It targets the "servers