
- name: SQL-Injection-Strings-In-URI|10.0.2.17
  hosts: servers
  become: yes
  tasks:
    - name: Block requests with SQL injection strings in URI
      uri:
        url: "http://example.com/api{{ item }}"
        method: GET
        status_code: 403
      with_items:
        - "/users?id=1'; DROP TABLE users;"
        - "/products?category=electronics'; DELETE FROM products;"
