---
- name: SQL Injection Strings In URI | 10.0.2.19
  hosts: servers
  become: yes
  tasks:
    - name: Block IP Address at Firewall
      iptables:
        chain: INPUT
        source: 10.0.2.19
        jump: DROP
